POST https://third.zcsazzurroportal.com:19003/
Content-Type: application/json
Authorization: Zcs eHWAeEq0aYO0

{
    "historicData": { 
        "client": "VanDerHam",
        "command": "historicData",
        "params" : {
          "thingKey": "ZM1ES030M5R243",
          "requiredValues": "*",
          "start": "2022-01-19T00:00:00.000Z",
          "end": "2022-01-19T23:59:59.059Z"
      }
   }
}
