POST https://third.zcsazzurroportal.com:19003/
Content-Type: application/json
Authorization: Zcs eHWAeEq0aYO0

{
    "realtimeData": { 
        "client": "VanDerHam",
        "command": "realtimeData",
        "params" : {
          "thingKey": "ZM1ES030M5R243",
          "requiredValues": "*"
        }
   }
}